name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: orders-service

    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
      - name: Build JAR
        run: mvn install -B
               
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'   
       
      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory:"
          ls -al
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "GitHub home: $GITHUB_HOME"
          echo "GitHub workflow: $GITHUB_WORKFLOW"
          echo "GitHub event path: $GITHUB_EVENT_PATH"
          echo "GitHub repository: $GITHUB_REPOSITORY"
          echo "GitHub run ID: $GITHUB_RUN_ID"
          echo "GitHub run number: $GITHUB_RUN_NUMBER"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GitHub ref: $GITHUB_REF"

  
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=CAScompany_project-OrderService
            -Dsonar.organization=cascompany
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.sources=src/main/java
