name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: orders-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: orders-service/

      - name: Maven test 
        run: mvn install -B 
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'
      

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=CAScompany_project-OrderService
            -Dsonar.organization=cascompany
            -Dsonar.sources=src/main/java
            -Dsonar.tests=orders-service/src/test/java/uy/edu/ort/devops/ordersserviceexample
            -Dsonar.junit.reportsPath=orders-service/target/surefire-reports/
            -Dsonar.junit.reportsPath=orders-service/target/checkstyle-result.xml  
            -Dsonar.jacoco.reportPaths=orders-service/target/jacoco.exec
            -Dsonar.java.checkstyle.reportPath=orders-service/target/checkstyle-result.xml  
            -Dsonar.java.binaries=orders-service/src/test/java/uy/edu/ort/devops/ordersserviceexample
            -X
